steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://calorify-pi/.env", "./.env"]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "cp",
        "gs://calorify-pi/serviceAccountKey.json",
        "./serviceAccountKey.json",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "app"
      - "deploy"
    timeout: "600s"

options:
  logging: "CLOUD_LOGGING_ONLY"
